# deploy do mongodb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.6
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd
---
# service do mongodb
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
  type: ClusterIP
---
#Deployment da app web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: marciovsantos/rotten-potatoes:1.0
        ports:
          - containerPort: 5000
        env:
        - name: MONGO_DB
          value: "admin"
        - name: MONGODB_HOST
          value: "mongodb"
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: "mongouser"
        - name: MONGODB_PASSWORD
          value: "mongopwd"
---
#Service da app web
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: LoadBalancer

#para subir uma imagem local no kind sem precisar enviar para o docker hub
#kind --name meucluster load docker-image marciovsantos/rotten-potatoes:1.0 